sudo: required

dist: trusty

notifications:
  email: false
  slack:
    secure: eRyL6uJ1ZZTO5xdq9BnndpVpSiygMdNRSEWL9hUDxTJKOH1zvTOz0tZsqcmqpSu6W9kY8kcXhg3MWP0kC7AXOMkyK64e/DTjnLySLk2N+uYYP6Mqc+Ke1kedS0SXi6Sxtr+7xvWHbHCPiRZWC6lddDakfboKDA7HWR2qbC9pvkM=

before_script:
  - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3
  - bash --version
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
  - source /home/travis/.bashrc
  - nvm --version
  - nvm install v4.2.4
  - npm -v
  - which npm
  - n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local
  - n=$(which npm);n=${n%/bin/npm}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local
  - npm install -g bower
  - npm install -g grunt-cli

script:
  - bower install
  - npm install
  - grunt checkout
  - grunt eslint
